FROM nginx
LABEL maintainer="sarthak<sk@gmail.com>"

COPY /home/sk/Documents/aws/Ex_Files__Kubernetes_Your_First_Project/03_02_after/website /website
COPY /home/sk/Documents/aws/Ex_Files__Kubernetes_Your_First_Project/03_02_before/nginx.conf /etc/nginx/nginx.conf


 