apiVersion: v1
kind: Service 
metadata: 
  name: test-service
  annotations:
    service.beta.kubernetes.io/linode-loadblanacer-throttle: "4"
  labels:
    app: test-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nccoffee
  sessionAffinity: None
